services:
  database:
    container_name: database
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      PGDATA: ${POSTGRES_PGDATA}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - db-network
    restart: always

volumes:
  postgres_data:

networks:
  db-network:
